config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  post 'book_for_user', to: 'bookings#book_for_user', as: :book_for_user

  resources :users, only: [:edit, :update]

  resources :teachers, only: [:index, :show, :new, :create, :edit, :update]
  resources :slots, only: [:index, :new, :create, :destroy, :update] do
    get 'change', to: 'slots#change', as: :change
    patch 'reserve', to: 'slots#reserve', as: :reserve
    patch 'bookable', to: 'slots#bookable', as: :bookable
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index] do
    patch 'cancel', to: 'bookings#cancel', as: :cancel
  end
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :teacher
  has_many :bookings

  DURATION = [60, 90, 120]

  validates :duration, inclusion: { in: DURATION }
  validate :date_have_to_be_in_the_future

  delegate :user, to: :teacher
  
  def booked?
    self.provisional == false && !self.bookings.where(status: true).empty?
  end

  def reserved?
    self.provisional == false
  end

  def booking_active
    self.bookings.where(status: true).first
  end

  def number_of_slots
    if self.duration == 60
      4
    elsif self.duration == 90
      6
    else
      8
    end
  end

  def student
    self.booking_active.user
  end

  def date_have_to_be_in_the_future
    if start_time < DateTime.current.to_date
      errors.add(:base, "start time can't be in the past")
    end
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  def index
    @slots = policy_scope(Slot)
    @slot = Slot.new
  end

  def new
    @slot = Slot.new
    authorize @slot
  end

  def create
    start_time = DateTime.strptime(params[:date], '%d/%m/%Y, %H:%M:%S')
    @slot = Slot.new(start_time: start_time, teacher_id: current_user.teacher.id)
    authorize @slot
    if @slot.save!
      redirect_to slots_path, notice: "The slot was created!"
    else
      redirect_to slots_path, notice: "Sorry, something went wrong"
    end
  end

  def update
    @slot = Slot.find(params[:id])
    authorize @slot
    if @slot.update(duration: params[:duration])
      redirect_to slots_path, notice: "The slot was updated!"
    else
      redirect_to slots_path, notice: "Sorry, something went wrong"
    end
  end

  def reserve
    @slot = Slot.find(params[:slot_id])
    authorize @slot
    if @slot.update(provisional: false) && @slot.bookings.destroy_all
      redirect_to slots_path, notice: "The slot was reserve!"
    else
      redirect_to slots_path, notice: "Sorry, something went wrong"
    end
  end

  def bookable
    @slot = Slot.find(params[:slot_id])
    authorize @slot
    if @slot.update(provisional: true)
      redirect_to slots_path, notice: "The slot is now bookable!" 
    else
      redirect_to slots_path, notice: "Sorry, something went wrong" 
    end
  end

  def change
    @slot = Slot.find(params[:slot_id])
    authorize @slot
  end

  def destroy
    @slot = Slot.find(params[:id])
    authorize @slot
    @slot.bookings.destroy_all
    if @slot.destroy
      redirect_to slots_path, notice: "The slot was deleted!"
    else
      redirect_to slots_path, notice: "Sorry, something went wrong" 
    end
  end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_change_form.html.erb
<% if @slot.booked? %>
  <div class="form-change booked change-form">
    <a data-id="<%= @slot.id%>" href="#" ><%= fa_icon "window-close", class: "close white-link mx-2" %></a>
    <p><%= @slot.start_time.strftime("%H:%M") %>  - <%= @slot.duration%> mins <br></p>
    <%= link_to 'Cancel this booking', booking_cancel_path(@slot.booking_active), method: :patch, class: "btn btn-outline-light my-2"%>
    <%= link_to "See details", teacher_path(@slot.teacher), class: "btn btn-outline-light" %>
  </div>
<% elsif @slot.reserved? %>
  <div class="form-change reserved change-form">
    <a data-id="<%= @slot.id%>" href="#" ><%= fa_icon "window-close", class: "close white-link mx-2" %></a>
    <p><%= @slot.start_time.strftime("%H:%M") %>  - <%= @slot.duration%> mins <br></p>
    <%= link_to 'Make it bookable', slot_bookable_path(@slot), method: :patch, class: "btn btn-outline-light my-2"%>
    <%= link_to 'Book a class', new_slot_booking_path(@slot), class: "btn btn-outline-light my-2"%>
  </div>
<% else %>
  <div class="form-change free change-form">
    <a data-id="<%= @slot.id%>" href="#" ><%= fa_icon "window-close", class: "close white-link mx-2" %></a>
    <p><%= @slot.start_time.strftime("%H:%M") %>  - <%= @slot.duration%> mins <br></p>
    <%= link_to 'Reserve this slot', slot_reserve_path(@slot), method: :patch, class: "btn btn-outline-light my-2"%>
    <%= link_to 'Book a class', new_slot_booking_path(@slot), class: "btn btn-outline-light my-2"%>
  </div>
<% end %>

app/views/slots/_form.html.erb
 <%= simple_form_for @slot, remote: true do |f| %>
    <%= f.input :start_time, label: "Please insert the date and start time" %>
    <%= f.input :duration, collection: Slot::DURATION, label: "How long will it take?" %>
    <%= f.submit %>
  <% end %>

app/views/slots/_modal.html.erb
<div class="modal fade" id="bookClass" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= simple_form_for Booking.new, as: :booking, method: :post, url: book_for_user_path do |f| %>
            <%= f.input :id, as: :hidden %>
            <%= f.association :user, collection: User.where.not(id: current_user.id), label: 'Enter the student name:' %>
            <%= f.button :submit, class:"btn btn-outline-secondary my-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/slots/_slot.html.erb
  <div class="card my-2 mx-2" style="width: 18rem;">
    <div class="card-body text-center">
      <h5 class="card-title"><%= slot.start_time.strftime("%d/%m/%Y") %> </h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= slot.start_time.strftime("%H:%M") %>  - <%= slot.duration%> mins </h6>
      <%= link_to 'Reserve this slot', slot_reserve_path(slot), method: :patch, class: "btn btn-outline-secondary my-2 reserve", data: { remote: true } %>
      <a href="#" class="btn btn-outline-secondary my-2">Book a class</a>
    </div>
  </div>

app/views/slots/change.js.erb
$('#<%= @slot.id %> a').hide().parent().append('<%= j render 'change_form', slot: @slot %>')

app/views/slots/create.html.erb
<h1>Slots#create</h1>
<p>Find me in app/views/slots/create.html.erb</p>

app/views/slots/create.js.erb
$('#new-slot form').remove();
$('#new-slot a').show();
$('#slots-list').append('<%= j render @slot %>');

app/views/slots/index.html.erb
<div class="my-5 mx-3">
  <%= week_calendar(number_of_weeks: 1, events: @slots) do |date, meetings| %>
    <%= date %>
    <ul 
      id="<%= date.day.to_s.split('').size == 1 ? date.day.to_s.split('').prepend('0').join : date.day %><%= date.month.to_s.split('').size == 1 ? date.month.to_s.split('').prepend('0').join : date.month%><%= date.year%>" 
      class="day">
    <% hour = '0600' %>
    <% while hour != '2300' %>
      <% array_hour = hour.split('') %>
      <% minutes = array_hour[2] + array_hour[3] %>
      <% if minutes == '00' || minutes == '15' || minutes == '30' %>
       <% hour = (hour.to_i + 15).to_s %>
       <% hour = hour.split('').unshift('0').join if hour.split('').size == 3 %>
       <li class="slice <%= hour%>" data-hour=<%= hour%>><%= hour%></li>
       <% elsif minutes == '45' %>
       <% hour = (hour.to_i + 55).to_s %>
       <% hour = hour.split('').unshift('0').join if hour.split('').size == 3 %>
       <li class="slice <%= hour%>" data-hour=<%= hour%>><%= hour%></li>
      <% end %>
    <% end %>
    </ul>
    
    <% meetings.each do |meeting| %>

      <% if meeting.booked? %>
        <div class="calendar-entry p-2"
            data-id="<%=meeting.id %>"
            data-day="<%=meeting.start_time.strftime("%d%m%Y") %>"
            data-hour="<%=meeting.start_time.strftime("%H%M") %>"
            data-duration-number="<%=meeting.number_of_slots %>">

            <div class="d-flex justify-content-end">
              <%= fa_icon "trash", class: "close-card black-link mx-2 delete-slot" %>
            </div>
            <div class="start-hour my-3">
              <div class="color-box mr-2 booked"></div>
              <p class="d-block"><%=meeting.start_time.strftime("%b %e, %l:%M %p") %></p>
            </div>
            <div class="d-flex justify-content-around my-1">
              <% if meeting.duration == Slot::DURATION[0] %>
                <div class="duration-box active-box"><%=Slot::DURATION[0]%></div>
              <% else %>
              <div class="duration-box"><%=Slot::DURATION[0]%></div>
              <% end %>
              <% if meeting.duration == Slot::DURATION[1] %>
                <div class="duration-box active-box"><%=Slot::DURATION[1]%></div>
              <% else %>
              <div class="duration-box"><%=Slot::DURATION[1]%></div>
              <% end %>
              <% if meeting.duration == Slot::DURATION[2] %>
                <div class="duration-box active-box"><%=Slot::DURATION[2]%></div>
              <% else %>
              <div class="duration-box"><%=Slot::DURATION[2]%></div>
              <% end %>
            </div>
            <div class="booked-class my-2">
              <%= link_to booking_cancel_path(meeting.booking_active), method: :patch, class: "book-link my-1" do %>
              <%= fa_icon "user", class:"mr-3" %>Cancel Class
              <%end%>
              <div class="d-flex align-items-center my-2">
                <% if meeting.student.photo.attached? %>
                  <%= cl_image_tag meeting.student.photo.key, class: "avatar" %><p class="d-flex ml-2"><%= meeting.student.full_name %></p>
                <% else %>
                  <%= image_tag "user.jpg", class: "avatar"%><p class="d-flex ml-2"><%= meeting.student.full_name %></p>
                <% end %>
              </div>
            </div>
          </div>
      <% elsif meeting.reserved? %>
        <div class="calendar-entry p-2"
          data-id="<%=meeting.id %>"
          data-day="<%=meeting.start_time.strftime("%d%m%Y") %>"
          data-hour="<%=meeting.start_time.strftime("%H%M") %>"
          data-duration-number="<%=meeting.number_of_slots %>">

          <div class="d-flex justify-content-end">
            <%= fa_icon "trash", class: "close-card black-link mx-2 delete-slot" %>
          </div>
          <div class="start-hour my-3">
            <div class="color-box mr-2 reserved"></div>
            <p class="d-block"><%=meeting.start_time.strftime("%b %e, %l:%M %p") %></p>
          </div>
          <div class="d-flex justify-content-around my-1">
            <% if meeting.duration == Slot::DURATION[0] %>
              <div class="duration-box active-box"><%=Slot::DURATION[0]%></div>
            <% else %>
            <div class="duration-box"><%=Slot::DURATION[0]%></div>
            <% end %>
            <% if meeting.duration == Slot::DURATION[1] %>
              <div class="duration-box active-box"><%=Slot::DURATION[1]%></div>
            <% else %>
            <div class="duration-box"><%=Slot::DURATION[1]%></div>
            <% end %>
            <% if meeting.duration == Slot::DURATION[2] %>
              <div class="duration-box active-box"><%=Slot::DURATION[2]%></div>
            <% else %>
            <div class="duration-box"><%=Slot::DURATION[2]%></div>
            <% end %>
          </div>
          <div class="link-container">
            <a class="my-1 unreserve-link"><%= fa_icon "toggle-off", class:"mr-3" %> Make it bookable </a>
          </div>
        </div>
      <% else %>
        <div class="calendar-entry p-2"
          data-id="<%=meeting.id %>"
          data-day="<%=meeting.start_time.strftime("%d%m%Y") %>"
          data-hour="<%=meeting.start_time.strftime("%H%M") %>"
          data-duration-number="<%=meeting.number_of_slots %>">

          <div class="d-flex justify-content-end">
            <%= fa_icon "trash", class: "close-card black-link mx-2 delete-slot" %>
          </div>
          <div class="start-hour my-3">
            <div class="color-box mr-2 free"></div>
            <p class="d-block"><%=meeting.start_time.strftime("%b %e, %l:%M %p") %></p>
          </div>
          <div class="d-flex justify-content-around my-1">
            <% if meeting.duration == Slot::DURATION[0] %>
              <div class="duration-box active-box"><%=Slot::DURATION[0]%></div>
            <% else %>
            <div class="duration-box"><%=Slot::DURATION[0]%></div>
            <% end %>
            <% if meeting.duration == Slot::DURATION[1] %>
              <div class="duration-box active-box"><%=Slot::DURATION[1]%></div>
            <% else %>
            <div class="duration-box"><%=Slot::DURATION[1]%></div>
            <% end %>
            <% if meeting.duration == Slot::DURATION[2] %>
              <div class="duration-box active-box"><%=Slot::DURATION[2]%></div>
            <% else %>
            <div class="duration-box"><%=Slot::DURATION[2]%></div>
            <% end %>
          </div>
          <div class="link-container">
            <a class="my-1 reserve-link"><%= fa_icon "toggle-off", class:"mr-3" %> Reserve</a>
            <a class="book-link my-1"
            data-id="<%=meeting.id %>" 
            data-date="<%=meeting.start_time.strftime("%d/%m/%Y - %H:%M") %>">
            <%= fa_icon "user", class:"mr-3" %>Book Class
            </a>
          </div>
        </div>
      <% end %>
      <%= render 'modal', slot: meeting %>
    <% end %>
  <% end %>
  <div class='my-legend my-3'>
    <div class='legend-scale'>
      <ul class='legend-labels'>
        <li><span class="booked"></span>Class booked</li>
        <li><span class="free"></span>Available for booking</li>
        <li><span class="reserved"></span>Reserved</li>
      </ul>
    </div>
  </div>
</div>

app/views/slots/new.js.erb
$('#new-slot .btn').hide().parent().append('<%= j render 'form', slot: @slot %>')

app/views/slots/reserve.js.erb
$('.reserve').bind('ajax:success', function(){
  $(this).closest('.card').fadeOut();
});