config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  post 'book_for_user', to: 'bookings#book_for_user', as: :book_for_user

  resources :users, only: [:edit, :update]

  resources :teachers, only: [:index, :show, :new, :create, :edit, :update]
  resources :slots, only: [:index, :new, :create, :destroy, :update] do
    get 'change', to: 'slots#change', as: :change
    patch 'reserve', to: 'slots#reserve', as: :reserve
    patch 'bookable', to: 'slots#bookable', as: :bookable
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index] do
    patch 'cancel', to: 'bookings#cancel', as: :cancel
  end
end

app/views/shared/_flashes.html.haml
- if notice
  .alert.alert-info.alert-dismissible{role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
    = notice
- if alert
  .alert.alert-warning.alert-dismissible{role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
    = alert

app/views/shared/_navbar.html.haml
.navbar.navbar-expand-sm.navbar-light.navbar-lewagon
  .container
    = link_to root_path, class: "navbar-brand" do
      - image_tag "dance.png", alt: "Dancing"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        - if user_signed_in?
          %li.nav-item
            = link_to "Teachers", teachers_path, class: "nav-link"
          %li.nav-item
            - if policy(Slot).create?
              = link_to "Teacher dashboard", slots_path, class: "nav-link"
          %li.nav-item
            = link_to "Student dashboard", bookings_path, class: "nav-link"
          %li.nav-item.dropdown
            - if current_user.photo.attached?
              = cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false
            - else
              = image_tag "user.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
              - if policy(Teacher).new?
                = link_to "Become a teacher", new_teacher_path, class: "dropdown-item"
              - if policy(Teacher).edit?
                = link_to "Edit my profile", edit_teacher_path(current_user.teacher), class: "dropdown-item"
              - else
                = link_to "Edit my profile", edit_user_path(current_user), class: "dropdown-item"
              = link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          %li.nav-item
            = link_to "Login", new_user_session_path, class: "nav-link"